### PR TITLE
Drag&Drop Fix

### PR DESCRIPTION
**Pull request by Snaggly**
Allowing this access by default will prevent the issue as noted in #260 .

This will also prevent the application from crashing when you open one ROM File with Yuzu from the system file explorer.

### CODE REVIEW

**Comment by liushuyu** [comment]
Hi, sorry for the very late reply.

Can you split this pull request into two pull requests? One may only contain Discord fix and one contains the drag-and-drop fix, so they will be easily trackable for me. (And you will get two pull requests merged)

> This will also prevent the application from crashing when you open one ROM File with Yuzu from the system file explorer.

To my understanding, this is actually a design flaw in Flatpak. Some users voted against accessing `/home` in the past, I am not sure how they would feel about this change.

Regardless, the changes themselves look good to me and thank you for your contribution!

**Comment by Snaggly** [comment]
Hello @liushuyu , thank you for getting back to me! I reverted the changes for Discord Rich Presence in this branch. I created a new branch and started a new pull request in #328 .

Initially I intended to have two pull requests, but I failed to understand that new commits in the same branch automatically add up to the already existing pull request, hence the sudden renaming.

**Comment by liushuyu** [comment]
> Hello @liushuyu , thank you for getting back to me! I reverted the changes for Discord Rich Presence in this branch. I created a new branch and started a new pull request in #328 .
> 
> Initially I intended to have two pull requests, but I failed to understand that new commits in the same branch automatically add up to the already existing pull request, hence the sudden renaming.

No problem. I have merged the other pull request, which created a merge conflict on this pull request.

Can you do a `git rebase` on this branch?

**Comment by liushuyu** [comment]
There seems to be an issue with your _merge_. You seem to have erased your changes.

**Comment by liushuyu** [comment]
Okay, it seems like your rebase just now worked.

Do you want me to do a squash merge now or do you want to clean up the commit history?

**Comment by Snaggly** [comment]
@liushuyu Do so as you please. This pull request with the commit history looks honestly terrible. I wish I did this on a new branch...

**Comment by liushuyu** [comment]
> @liushuyu Do so as you please. This pull request with the commit history looks honestly terrible. I wish I did this on a new branch...

Don't worry, let me help you:

In this case, you want to first look at which commit you want to keep. In your case, it's this one:

```
commit 7c43584ddc41990cffc02dc6c638279de40d903f
Author: Snaggly <***>
Date:   Sun Feb 6 11:21:05 2022 +0100

    Allow access to read home and external harddrives
```

Note down the _commit hash_, and let's rewind your branch (**WARNING**: this will erase the commit history!): `git reset --hard HEAD~20`

Then _re-sync_ with this repository: `git pull --ff-only https://github.com/flathub/org.yuzu_emu.yuzu master`

Now you want to re-apply this commit on top of the new commit history: `git cherry-pick 7c43584ddc41990cffc02dc6c638279de40d903f`

Then Git will ask you to resolve the conflicts. You need to resolve the conflicts per normal and `git add org.yuzu_emu.yuzu.json`. After that, `git commit --amend -S` to sign your commit, then `git cherry-pick --continue` to tell Git that you are done.

Finally, push your changes with `git push --force`.

**Comment by Snaggly** [comment]
@liushuyu Thanks a lot! I managed to clean up the mess I created on my head :+1:

**Comment by liushuyu** [comment]
> @liushuyu Thanks a lot! I managed to clean up the mess I created on my head +1

No problem! However, it seems like you brought the other commit with you as well, this created another merge conflict.

You can fix this by `git rebase -i HEAD~2` then change the command list to the following:

```
drop 99d2717 Add Discord Rich Presence Support
pick 8488d7d Allow access to read home and external harddrives
```

Save the command list and `git commit --amend -S` to re-sign your commit.

**Comment by liushuyu** [comment]
Oh I forgot, if you encountered conflict resolution, do it like before. But end it with `git rebase --continue` instead of `git cherry-pick --continue`.

**Comment by liushuyu** [comment]
Merged in e333fb7d815f7a28160fa3dc6d11ce513a8eb524.

**Pull request closed without merging**
