### PR TITLE
Remove host filesystem access

### PR DESCRIPTION
**Pull request by jannuary**
Removes read-only access to the entire host filesystem. As far as I know, yuzu already can get files from xdg-desktop-portal, so this shouldn't remove or break anything.

### CODE REVIEW

**Comment by jannuary** [comment]
Ah of course, can't go without typos.

**Comment by liushuyu** [comment]
Sorry for the late reply. Please rebase your branch and I will merge it.

**Comment by liushuyu** [comment]
It seems like there are some CI errors that are not your fault. I will take the commit content and merge it using the patch created from your pull request (your authorship will be preserved).

**Comment by liushuyu** [comment]
Your pull request is lumped into 0f83cd49a17a72bc099cb394db3e9eabdd16e2ba (in #224).

I will merge that pull request shortly.

**Pull request closed without merging**
